import esmodule
from elasticsearch import Elasticsearch

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_USER = "grace"
ELASTIC_PASSWORD = "88888888"

# Found in the 'Manage Deployment' page
CLOUD_ID = "datacenter:dXMtY2VudHJhbDEuZ2NwLmNsb3VkLmVzLmlvOjQ0MyQ4ZjdkMTc3NWRkZWI0NmZhYTM5MDc0YmE1ZTY2MDkwZiRmZDcxYTYzOGJhODk0MGM2OWZhOWY0YmQyYTczYWFmNw=="
API_KEY = "eDl3RlRZY0JfeUlUUWkxVGVIdXg6VmxGQjA2VUpURHFpYUpLQ1Q2QjZldw=="

# Create the client instance
# es_client = Elasticsearch(cloud_id = CLOUD_ID, basic_auth=(ELASTIC_USER, ELASTIC_PASSWORD))
es_client = Elasticsearch(cloud_id = CLOUD_ID, api_key = API_KEY)

# Successful response!
print(es_client.info())

esmodule.insert_es_index(es_client)
esmodule.queryAll(es_client, "test-index")